apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app-b-config
  namespace: web-app-b
data:
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  APP_NAME: "web-app-b"
  PORT: "8080"
  REGION: "OVERRIDDEN_BY_OVERLAY"
  PUBSUB_TOPIC: "web-app-b-events"
  REDIS_HOST: "OVERRIDDEN_BY_OVERLAY"
