apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web-app-b
resources:
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - backendconfig.yaml
commonLabels:
  app.kubernetes.io/name: web-app-b
  app.kubernetes.io/part-of: platform
