apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app-a-config
  namespace: web-app-a
data:
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  APP_NAME: "web-app-a"
  PORT: "8080"
  REGION: "OVERRIDDEN_BY_OVERLAY"
