apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-app-a
  namespace: web-app-a
  annotations:
    iam.gke.io/gcp-service-account: web-app-a-sa@PROJECT_ID.iam.gserviceaccount.com  # overlaid per env
